#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += hx83102d_hdp_dsi_vdo_truly_truly_zal3251.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc