#
LOCAL_DIR := $(GET_LOCAL_DIR)
TARGET := k65v1_64_bsp
MODULES += app/mt_boot \
           dev/lcm
           
MTK_EMMC_SUPPORT = yes
MTK_MMC_COMBO_DRV = yes
MTK_EMMC_SUPPORT_OTP = yes
MTK_SMI_SUPPORT = yes
MTK_KERNEL_POWER_OFF_CHARGING = yes
DEFINES += MTK_NEW_COMBO_EMMC_SUPPORT
DEFINES += MTK_GPT_SCHEME_SUPPORT

MTK_CHARGER_NEW_ARCH := yes
MTK_PUMP_EXPRESS_PLUS_SUPPORT := yes
MTK_MT6370_PMU_CHARGER_SUPPORT := yes
MTK_MT6370_PMU_BLED_SUPPORT := yes
MTK_CHARGER_INTERFACE := yes

# LCM Configuration
MTK_LCM_PHYSICAL_ROTATION = 0
CUSTOM_LK_LCM = "hx83102d_hdp_dsi_vdo_truly_truly_zal3251"
DEFINES += HX83102D_HDP_DSI_VDO_TRULY_TRULY_ZAL3251
DEFINES += MTK_ROUND_CORNER_SUPPORT

# Boot Logo (720x1600)
BOOT_LOGO := hd720
# Debug
DEBUG := 2
DEFINES += WITH_DEBUG_UART=1

# USB
CUSTOM_LK_USB_UNIQUE_SERIAL=no

# SCP/SSPM
MTK_TINYSYS_SCP_SUPPORT = yes
MTK_TINYSYS_SSPM_SUPPORT = yes

# Modem Config
MTK_PROTOCOL1_RAT_CONFIG = C/Lf/Lt/W/T/G

# Security Settings - Disable for development
MTK_VERIFIED_BOOT_SUPPORT = no
MTK_SECURITY_SW_SUPPORT =yes
MTK_SEC_FASTBOOT_UNLOCK_SUPPORT = yes
MTK_SEC_USBDL = no
MTK_SECURITY_ANTI_ROLLBACK = no
SPM_FW_USE_PARTITION = yes
MTK_GOOGLE_TRUSTY_SUPPORT = no
MTK_EFUSE_WRITER_SUPPORT = no
MTK_SMC_ID_MGMT = yes

# Other
MTK_AB_OTA_UPDATER = no
DEVELOP_STAGE = SB
MTK_LK_ENABLE_DCM = yes
MTK_MT22_MODE := H1
MTK_ENABLE_GENIEZONE = yes
DEFINES += NO_POWER_OFF=y

# key

MT6765_USE_FCHR_ENB_KEY = yes
