#
LOCAL_DIR := $(GET_LOCAL_DIR)
TARGET := k65v1_64_bsp
MODULES += app/mt_boot \
           dev/lcm

MTK_EMMC_SUPPORT = yes
MTK_MMC_COMBO_DRV = yes
MTK_EMMC_SUPPORT_OTP = yes
MTK_SMI_SUPPORT = yes
MTK_KERNEL_POWER_OFF_CHARGING = yes
DEFINES += MTK_NEW_COMBO_EMMC_SUPPORT
DEFINES += MTK_GPT_SCHEME_SUPPORT

MTK_CHARGER_NEW_ARCH := yes
MTK_PUMP_EXPRESS_PLUS_SUPPORT := yes
MTK_MT6370_PMU_CHARGER_SUPPORT := yes
MTK_MT6370_PMU_BLED_SUPPORT := yes
MTK_CHARGER_INTERFACE := yes

# LCM Configuration
MTK_LCM_PHYSICAL_ROTATION = 0
CUSTOM_LK_LCM = "hx83102d_hdp_dsi_vdo_truly_truly_zal3251"
DEFINES += HX83102D_HDP_DSI_VDO_TRULY_TRULY_ZAL3251
DEFINES += MTK_ROUND_CORNER_SUPPORT

# Boot Logo (720x1600)
BOOT_LOGO := hdplus1600

# Debug
DEBUG := 2
DEFINES += WITH_DEBUG_UART=1

# USB
CUSTOM_LK_USB_UNIQUE_SERIAL=yes
DEFINES += SERIAL_NUM_FROM_BARCODE=1

# SCP/SSPM
MTK_TINYSYS_SCP_SUPPORT = yes
MTK_TINYSYS_SSPM_SUPPORT = yes

# Modem Config
MTK_PROTOCOL1_RAT_CONFIG = C/Lf/Lt/W/T/G

# from stock
SYSTEM_AS_ROOT = yes
MTK_DTBO_FEATURE = yes
MTK_APPENDED_DTB_SUPPORT = no
MTK_BACKLIGHT_SMOOTH_SUPPORT = yes
MTK_LCM_DEVICE_TREE_SUPPORT = no
MTK_DISPLAY_CUTOUT_POLICY = 0

# ============================================================
# FORCE DISABLE AVB COMPLETELY
# ============================================================
MTK_VERIFIED_BOOT_SUPPORT = no
MTK_SECURITY_SW_SUPPORT = no
MTK_SEC_FASTBOOT_UNLOCK_SUPPORT = no
MTK_SEC_USBDL = no
MTK_SECURITY_ANTI_ROLLBACK = no
MTK_EFUSE_WRITER_SUPPORT = no
MTK_SMC_ID_MGMT = no
MTK_GOOGLE_TRUSTY_SUPPORT = no
SPM_FW_USE_PARTITION = no

# AVB 2.0 Disable
DEFINES += AVB20_DISABLE=1
DEFINES += AVB20_DISABLE_AVB=1
DEFINES += AVB2_DISABLE=1
DEFINES += MTK_AVB20_SUPPORT=0
DEFINES += MTK_SECURITY_OFF=1
DEFINES += MTK_SEC_CTRL_SUPPORT=n
DEFINES += MTK_EFUSE_SUPPORT=n

# Other
MTK_AB_OTA_UPDATER = no
DEVELOP_STAGE = SB
MTK_LK_ENABLE_DCM = yes
MTK_MT22_MODE := H1
MTK_ENABLE_GENIEZONE = yes
DEFINES += NO_POWER_OFF=y

# key
MT6765_USE_FCHR_ENB_KEY = yes
