name: Build workflow

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lk-build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
      
    - name: Install python2
      run: |
        sudo apt-get update
        sudo apt-get install -y python2
        sudo ln -s /usr/bin/python2 /usr/bin/python || true
        python2 --version
        
    - name: Build the bootloader
      run: make X5
      
    - name: Upload bootloader
      uses: actions/upload-artifact@v4
      with:
        name: X5_lk-signed.img
        path: build-X5/lk-sign.img
